export { default as referral } from './referral.png';
export { default as score } from './score.png';
export { default as balance } from './balance.png';
export { default as average } from './average.png';
export { default as puzzle } from './puzzle.png';
export { default as excel } from './excel.png';
export { default as coming } from './coming-soon.png';
export { default as crypto } from './crypto.png';
export { default as card } from './card.png';
export { default as paypal} from './paypal.png';
export { default as trophy } from './trophy.png';