export { default as mailRed } from './mailRed.png'
export { default as mailBlue } from './mailBlue.png'
export { default as mailGreen } from './mailGreen.png'
export { default as girlGreen } from './girl-green.png'
export { default as girlBlue } from './girl-blue.png'
export { default as girlRed } from './girl-red.png'
